version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/frontend-pi-iii/
permissions:
  - object: /var/www/html/frontend-pi-iii/
    pattern: '**'
    owner: ec2-user
    group: apache
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      runas: root
