export { type IAgent } from './IAgent';
export { type IAgentTicketHistory } from './IAgentTicketHistory';
export { type ICategory } from './ICategory';
export { type IConversation } from './IConversation';
export { type IMessage } from './IMessage';
export { type IRequester } from './IRequester';
export { type ISector } from './ISector';
export { type ITicket } from './ITicket';
export { type ILogin } from './ILogin';
